<a href="https://colab.research.google.com/github/shivi13102/Healthcare-Fraud-Provider-Detection-Analysis/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm

In [3]:
# Load Beneficiary Data
train_beneficiary = pd.read_excel('/content/drive/My Drive/FDS PROJECT/Train_Beneficiarydata-1542865627584.xlsx')
test_beneficiary = pd.read_excel('/content/drive/My Drive/FDS PROJECT/Test_Beneficiarydata-1542969243754.xlsx')

# Load Inpatient Data
train_inpatient = pd.read_excel('/content/drive/My Drive/FDS PROJECT/Train_Inpatientdata-1542865627584.xlsx')
test_inpatient = pd.read_excel('/content/drive/My Drive/FDS PROJECT/Test_Inpatientdata-1542969243754.xlsx')

# Load Outpatient Data
train_outpatient = pd.read_excel('/content/drive/My Drive/FDS PROJECT/Train_Outpatientdata-1542865627584.xlsx')
test_outpatient = pd.read_excel('/content/drive/My Drive/FDS PROJECT/Test_Outpatientdata-1542969243754.xlsx')

# Load General Train and Test Data
train_data = pd.read_excel('/content/drive/My Drive/FDS PROJECT/Train-1542865627584.xlsx')
test_data = pd.read_excel('/content/drive/My Drive/FDS PROJECT/Test-1542969243754.xlsx')

In [4]:
display(train_beneficiary)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,NaT,1,1,0,39,230,12,12,...,1,1,1,2,1,1,36000,3204,60,70
1,BENE11002,1936-09-01,NaT,2,1,0,39,280,12,12,...,2,2,2,2,2,2,0,0,30,50
2,BENE11003,1936-08-01,NaT,1,1,0,52,590,12,12,...,2,2,1,2,2,2,0,0,90,40
3,BENE11004,1922-07-01,NaT,1,1,0,39,270,12,12,...,2,1,1,1,1,2,0,0,1810,760
4,BENE11005,1935-09-01,NaT,1,1,0,24,680,12,12,...,2,1,2,2,2,2,0,0,1790,1200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138551,BENE159194,1939-07-01,NaT,1,1,0,39,140,12,12,...,2,2,2,2,2,2,0,0,430,460
138552,BENE159195,1938-12-01,NaT,2,1,0,49,530,12,12,...,2,1,2,2,2,2,0,0,880,100
138553,BENE159196,1916-06-01,NaT,2,1,0,6,150,12,12,...,1,1,1,2,2,2,2000,1068,3240,1390
138554,BENE159197,1930-01-01,NaT,1,1,0,16,560,12,12,...,2,2,1,2,2,2,0,0,2650,10
138555,BENE159198,1952-04-01,NaT,2,1,0,21,20,12,12,...,1,1,2,2,1,2,0,0,5470,1870

In [5]:
#Check the first few rows
print("The first 5 rows: ")
display(train_beneficiary.head())

The first 5 rows:

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,NaT,1,1,0,39,230,12,12,...,1,1,1,2,1,1,36000,3204,60,70
1,BENE11002,1936-09-01,NaT,2,1,0,39,280,12,12,...,2,2,2,2,2,2,0,0,30,50
2,BENE11003,1936-08-01,NaT,1,1,0,52,590,12,12,...,2,2,1,2,2,2,0,0,90,40
3,BENE11004,1922-07-01,NaT,1,1,0,39,270,12,12,...,2,1,1,1,1,2,0,0,1810,760
4,BENE11005,1935-09-01,NaT,1,1,0,24,680,12,12,...,2,1,2,2,2,2,0,0,1790,1200

In [6]:
#get the summary of the data
print("The Summary of the data:")
display(train_beneficiary.info())

The Summary of the data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138556 entries, 0 to 138555
Data columns (total 25 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   BeneID                           138556 non-null  object
 1   DOB                              138556 non-null  datetime64[ns]
 2   DOD                              1421 non-null    datetime64[ns]
 3   Gender                           138556 non-null  int64
 4   Race                             138556 non-null  int64
 5   RenalDiseaseIndicator            138556 non-null  object
 6   State                            138556 non-null  int64
 7   County                           138556 non-null  int64
 8   NoOfMonths_PartACov              138556 non-null  int64
 9   NoOfMonths_PartBCov              138556 non-null  int64
 10  ChronicCond_Alzheimer            138556 non-null  int64
 11  ChronicCond_Heartfailure         138556 non-null  int64
 12  ChronicCond_KidneyDisease        138556 non-null  int64
 13  ChronicCond_Cancer               138556 non-null  int64
 14  ChronicCond_ObstrPulmonary       138556 non-null  int64
 15  ChronicCond_Depression           138556 non-null  int64
 16  ChronicCond_Diabetes             138556 non-null  int64
 17  ChronicCond_IschemicHeart        138556 non-null  int64
 18  ChronicCond_Osteoporasis         138556 non-null  int64
 19  ChronicCond_rheumatoidarthritis  138556 non-null  int64
 20  ChronicCond_stroke               138556 non-null  int64
 21  IPAnnualReimbursementAmt         138556 non-null  int64
 22  IPAnnualDeductibleAmt            138556 non-null  int64
 23  OPAnnualReimbursementAmt         138556 non-null  int64
 24  OPAnnualDeductibleAmt            138556 non-null  int64
dtypes: datetime64[ns](2), int64(21), object(2)
memory usage: 26.4+ MB

None

In [7]:
#Describe the numerical columns
print("The numerical data: ")
display(train_beneficiary.describe())

The numerical data:

,DOB,DOD,Gender,Race,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,ChronicCond_Alzheimer,ChronicCond_Heartfailure,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
count,138556,1421,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,...,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000,138556.000000
mean,1936-04-30 16:46:00.772539520,2009-07-27 22:27:46.995073792,1.570932,1.254511,25.666734,374.424745,11.907727,11.910145,1.667817,1.506322,...,1.644476,1.398142,1.324143,1.725317,1.743180,1.920942,3660.346502,399.847296,1298.219348,377.718258
min,1909-01-01 00:00:00,2009-02-01 00:00:00,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-8000.000000,0.000000,-70.000000,0.000000
25%,1928-01-01 00:00:00,2009-06-01 00:00:00,1.000000,1.000000,11.000000,141.000000,12.000000,12.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,0.000000,0.000000,170.000000,40.000000
50%,1935-09-01 00:00:00,2009-08-01 00:00:00,2.000000,1.000000,25.000000,340.000000,12.000000,12.000000,2.000000,2.000000,...,2.000000,1.000000,1.000000,2.000000,2.000000,2.000000,0.000000,0.000000,570.000000,170.000000
75%,1941-12-01 00:00:00,2009-10-01 00:00:00,2.000000,1.000000,39.000000,570.000000,12.000000,12.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2280.000000,1068.000000,1500.000000,460.000000
max,1983-12-01 00:00:00,2009-12-01 00:00:00,2.000000,5.000000,54.000000,999.000000,12.000000,12.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,161470.000000,38272.000000,102960.000000,13840.000000
std,NaN,NaN,0.494945,0.717007,15.223443,266.277581,1.032332,0.936893,0.470998,0.499962,...,0.478674,0.489517,0.468056,0.446356,0.436881,0.269831,9568.621827,956.175202,2493.901134,645.530187

In [8]:
print("Shape of Train beneficiary data: ")
train_beneficiary.shape

Shape of Train beneficiary data:

(138556, 25)

#Data cleaning process for beneficiary data

In [9]:
# Check for missing values
missing_values = train_beneficiary.isnull().sum()
print(missing_values)

BeneID                                  0
DOB                                     0
DOD                                137135
Gender                                  0
Race                                    0
RenalDiseaseIndicator                   0
State                                   0
County                                  0
NoOfMonths_PartACov                     0
NoOfMonths_PartBCov                     0
ChronicCond_Alzheimer                   0
ChronicCond_Heartfailure                0
ChronicCond_KidneyDisease               0
ChronicCond_Cancer                      0
ChronicCond_ObstrPulmonary              0
ChronicCond_Depression                  0
ChronicCond_Diabetes                    0
ChronicCond_IschemicHeart               0
ChronicCond_Osteoporasis                0
ChronicCond_rheumatoidarthritis         0
ChronicCond_stroke                      0
IPAnnualReimbursementAmt                0
IPAnnualDeductibleAmt                   0
OPAnnualReimbursementAmt                0
OPAnnualDeductibleAmt                   0
dtype: int64

In [10]:
# Replace null values in the 'DOD' column with "Alive"
train_beneficiary['DOD'].fillna("Alive", inplace=True)

# Display the updated DataFrame
display(train_beneficiary)

<ipython-input-10-61e7ee8cdfde>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Alive' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  train_beneficiary['DOD'].fillna("Alive", inplace=True)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,Alive,1,1,0,39,230,12,12,...,1,1,1,2,1,1,36000,3204,60,70
1,BENE11002,1936-09-01,Alive,2,1,0,39,280,12,12,...,2,2,2,2,2,2,0,0,30,50
2,BENE11003,1936-08-01,Alive,1,1,0,52,590,12,12,...,2,2,1,2,2,2,0,0,90,40
3,BENE11004,1922-07-01,Alive,1,1,0,39,270,12,12,...,2,1,1,1,1,2,0,0,1810,760
4,BENE11005,1935-09-01,Alive,1,1,0,24,680,12,12,...,2,1,2,2,2,2,0,0,1790,1200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138551,BENE159194,1939-07-01,Alive,1,1,0,39,140,12,12,...,2,2,2,2,2,2,0,0,430,460
138552,BENE159195,1938-12-01,Alive,2,1,0,49,530,12,12,...,2,1,2,2,2,2,0,0,880,100
138553,BENE159196,1916-06-01,Alive,2,1,0,6,150,12,12,...,1,1,1,2,2,2,2000,1068,3240,1390
138554,BENE159197,1930-01-01,Alive,1,1,0,16,560,12,12,...,2,2,1,2,2,2,0,0,2650,10
138555,BENE159198,1952-04-01,Alive,2,1,0,21,20,12,12,...,1,1,2,2,1,2,0,0,5470,1870

In [11]:
# Display rows where 'DOD' does not contain "Alive"
non_alive_rows = train_beneficiary[train_beneficiary['DOD'] != "Alive"]

# Show the resulting DataFrame
display(non_alive_rows)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
6,BENE11007,1940-09-01,2009-12-01 00:00:00,1,2,0,45,610,12,12,...,2,1,2,1,1,2,0,0,1490,160
206,BENE11217,1939-07-01,2009-09-01 00:00:00,1,3,Y,5,160,12,12,...,1,1,1,1,1,2,0,0,3880,650
207,BENE11218,1928-12-01,2009-09-01 00:00:00,1,1,0,14,141,12,12,...,1,1,1,1,2,1,19000,1068,110,50
219,BENE11231,1937-12-01,2009-05-01 00:00:00,2,2,0,45,810,12,12,...,2,1,1,1,2,2,4000,1068,300,30
525,BENE11558,1927-12-01,2009-12-01 00:00:00,2,1,0,14,141,12,12,...,2,2,1,2,2,2,0,0,50,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137494,BENE158067,1939-06-01,2009-08-01 00:00:00,2,1,0,10,400,12,12,...,2,1,1,1,2,2,7000,1068,1190,320
137497,BENE158070,1919-11-01,2009-06-01 00:00:00,2,1,0,33,420,12,12,...,1,1,1,2,2,2,0,0,40,0
137682,BENE158266,1929-07-01,2009-12-01 00:00:00,1,3,0,5,400,12,12,...,1,1,1,2,1,2,20200,1068,2220,250
137859,BENE158455,1932-08-01,2009-05-01 00:00:00,1,1,0,21,10,12,12,...,2,2,2,2,2,2,4000,1068,0,0
138061,BENE158676,1927-01-01,2009-07-01 00:00:00,1,1,0,23,810,12,12,...,2,1,1,2,2,2,0,0,70,100

In [12]:
# Check for duplicates in the 'BeneID' column of the train_beneficiary dataset
duplicates = train_beneficiary[train_beneficiary.duplicated(subset='BeneID')]

# Print the result
if not duplicates.empty:
    print(f"Found {len(duplicates)} duplicates in the 'BeneID' column of train_beneficiary.")
    print(duplicates)
else:
    print("No duplicates found in the 'BeneID' column of train_beneficiary.")

# Count the number of unique values in the 'BeneID' column of the train_beneficiary dataset
unique_beneid_count = train_beneficiary['BeneID'].nunique()

# Print the result
print(f"There are {unique_beneid_count} unique values in the 'BeneID' column of train_beneficiary.")

No duplicates found in the 'BeneID' column of train_beneficiary.
There are 138556 unique values in the 'BeneID' column of train_beneficiary.

In [13]:
# Rename the 'county' column to 'country'
train_beneficiary = train_beneficiary.rename(columns={'County': 'Country'})

# Verify the change
print(train_beneficiary.columns)

Index(['BeneID', 'DOB', 'DOD', 'Gender', 'Race', 'RenalDiseaseIndicator',
       'State', 'Country', 'NoOfMonths_PartACov', 'NoOfMonths_PartBCov',
       'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
       'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
       'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
       'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
       'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
       'ChronicCond_stroke', 'IPAnnualReimbursementAmt',
       'IPAnnualDeductibleAmt', 'OPAnnualReimbursementAmt',
       'OPAnnualDeductibleAmt'],
      dtype='object')

In [14]:
# List of columns that need to be converted
chronic_conditions = [
    'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
    'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
    'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
    'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
    'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
    'ChronicCond_stroke'
]

# Convert 2 to 0 and leave 1 as 1 for the specified columns
train_beneficiary[chronic_conditions] = train_beneficiary[chronic_conditions].replace({2: 0})

# Verify the changes
display(train_beneficiary[chronic_conditions].head())

,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke
0,1,0,1,0,0,1,1,1,0,1,1
1,0,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,1,0,0,0
3,1,1,0,0,0,0,1,1,1,1,0
4,0,0,0,0,1,0,1,0,0,0,0

In [15]:
# Replace 0 with 'N' in the RenalDiseaseIndicator column
train_beneficiary['RenalDiseaseIndicator'] = train_beneficiary['RenalDiseaseIndicator'].replace({0: 'N'})

#Verify the changes
print(train_beneficiary['RenalDiseaseIndicator'].value_counts())

RenalDiseaseIndicator
N    118978
Y     19578
Name: count, dtype: int64

In [16]:
# Replace 1 with 'M' and 2 with 'F' in the gender column for train_beneficiary
train_beneficiary['Gender'] = train_beneficiary['Gender'].replace({1: 'M', 2: 'F'})

# Verify the changes
print(train_beneficiary['Gender'].value_counts())

Gender
F    79106
M    59450
Name: count, dtype: int64

In [17]:
display(train_beneficiary)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,Country,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,Alive,M,1,N,39,230,12,12,...,1,1,1,0,1,1,36000,3204,60,70
1,BENE11002,1936-09-01,Alive,F,1,N,39,280,12,12,...,0,0,0,0,0,0,0,0,30,50
2,BENE11003,1936-08-01,Alive,M,1,N,52,590,12,12,...,0,0,1,0,0,0,0,0,90,40
3,BENE11004,1922-07-01,Alive,M,1,N,39,270,12,12,...,0,1,1,1,1,0,0,0,1810,760
4,BENE11005,1935-09-01,Alive,M,1,N,24,680,12,12,...,0,1,0,0,0,0,0,0,1790,1200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138551,BENE159194,1939-07-01,Alive,M,1,N,39,140,12,12,...,0,0,0,0,0,0,0,0,430,460
138552,BENE159195,1938-12-01,Alive,F,1,N,49,530,12,12,...,0,1,0,0,0,0,0,0,880,100
138553,BENE159196,1916-06-01,Alive,F,1,N,6,150,12,12,...,1,1,1,0,0,0,2000,1068,3240,1390
138554,BENE159197,1930-01-01,Alive,M,1,N,16,560,12,12,...,0,0,1,0,0,0,0,0,2650,10
138555,BENE159198,1952-04-01,Alive,F,1,N,21,20,12,12,...,1,1,0,0,1,0,0,0,5470,1870

#Data cleaning of Test Beneficiary data

In [18]:
test_beneficiary.shape

(63968, 25)

In [19]:
# Check for missing values
missing_values = test_beneficiary.isnull().sum()
print(missing_values)

BeneID                                 0
DOB                                    0
DOD                                63394
Gender                                 0
Race                                   0
RenalDiseaseIndicator                  0
State                                  0
County                                 0
NoOfMonths_PartACov                    0
NoOfMonths_PartBCov                    0
ChronicCond_Alzheimer                  0
ChronicCond_Heartfailure               0
ChronicCond_KidneyDisease              0
ChronicCond_Cancer                     0
ChronicCond_ObstrPulmonary             0
ChronicCond_Depression                 0
ChronicCond_Diabetes                   0
ChronicCond_IschemicHeart              0
ChronicCond_Osteoporasis               0
ChronicCond_rheumatoidarthritis        0
ChronicCond_stroke                     0
IPAnnualReimbursementAmt               0
IPAnnualDeductibleAmt                  0
OPAnnualReimbursementAmt               0
OPAnnualDeductibleAmt                  0
dtype: int64

In [20]:
# Replace null values in the 'DOD' column with "Alive"
test_beneficiary['DOD'].fillna("Alive", inplace=True)

# Display the updated DataFrame
display(test_beneficiary)

<ipython-input-20-f086c6e048b8>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Alive' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  test_beneficiary['DOD'].fillna("Alive", inplace=True)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,Alive,1,1,0,39,230,12,12,...,1,1,1,2,1,1,36000,3204,60,70
1,BENE11007,1940-09-01,2009-12-01 00:00:00,1,2,0,45,610,12,12,...,2,1,2,1,1,2,0,0,1490,160
2,BENE11010,1936-07-01,Alive,2,1,0,41,30,12,12,...,2,1,1,1,2,2,0,0,1170,660
3,BENE11011,1914-03-01,Alive,2,2,0,1,360,12,12,...,1,1,2,2,1,1,5000,1068,250,320
4,BENE11014,1938-04-01,Alive,2,1,Y,45,780,12,12,...,1,2,1,2,2,2,21260,2136,120,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63963,BENE159187,1959-07-01,Alive,1,1,0,27,140,12,12,...,1,1,1,2,2,2,0,0,2650,450
63964,BENE159193,1936-12-01,Alive,2,1,0,36,170,12,12,...,2,2,2,2,2,2,0,0,110,50
63965,BENE159194,1939-07-01,Alive,1,1,0,39,140,12,12,...,2,2,2,2,2,2,0,0,430,460
63966,BENE159196,1916-06-01,Alive,2,1,0,6,150,12,12,...,1,1,1,2,2,2,2000,1068,3240,1390
63967,BENE159197,1930-01-01,Alive,1,1,0,16,560,12,12,...,2,2,1,2,2,2,0,0,2650,10

In [21]:
# Display rows where 'DOD' does not contain "Alive"
non_alive_rows2 = test_beneficiary[test_beneficiary['DOD'] != "Alive"]

# Show the resulting DataFrame
display(non_alive_rows2)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
1,BENE11007,1940-09-01,2009-12-01 00:00:00,1,2,0,45,610,12,12,...,2,1,2,1,1,2,0,0,1490,160
98,BENE11217,1939-07-01,2009-09-01 00:00:00,1,3,Y,5,160,12,12,...,1,1,1,1,1,2,0,0,3880,650
99,BENE11218,1928-12-01,2009-09-01 00:00:00,1,1,0,14,141,12,12,...,1,1,1,1,2,1,19000,1068,110,50
105,BENE11231,1937-12-01,2009-05-01 00:00:00,2,2,0,45,810,12,12,...,2,1,1,1,2,2,4000,1068,300,30
344,BENE11775,1910-08-01,2009-08-01 00:00:00,2,1,0,3,60,12,12,...,2,1,1,2,2,2,0,0,110,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63408,BENE157924,1937-05-01,2009-08-01 00:00:00,2,1,0,42,410,12,12,...,1,2,2,2,2,2,34000,1068,930,200
63450,BENE158030,1928-08-01,2009-04-01 00:00:00,2,1,0,10,120,12,12,...,1,1,1,1,2,2,0,0,160,30
63468,BENE158067,1939-06-01,2009-08-01 00:00:00,2,1,0,10,400,12,12,...,2,1,1,1,2,2,7000,1068,1190,320
63560,BENE158266,1929-07-01,2009-12-01 00:00:00,1,3,0,5,400,12,12,...,1,1,1,2,1,2,20200,1068,2220,250
63650,BENE158467,1942-09-01,2009-06-01 00:00:00,2,1,0,31,320,12,12,...,2,1,1,2,2,2,0,0,70,20

In [22]:
# Check for duplicates in the 'BeneID' column of the test_beneficiary dataset
test_duplicates = test_beneficiary[test_beneficiary.duplicated(subset='BeneID')]

# Print the result
if not test_duplicates.empty:
    print(f"Found {len(test_duplicates)} duplicates in the 'BeneID' column of test_beneficiary.")
    print(test_duplicates)
else:
    print("No duplicates found in the 'BeneID' column of test_beneficiary.")


# Unique values in test_beneficiary
unique_beneid_test_count = test_beneficiary['BeneID'].nunique()
print(f"There are {unique_beneid_test_count} unique values in the 'BeneID' column of test_beneficiary.")

No duplicates found in the 'BeneID' column of test_beneficiary.
There are 63968 unique values in the 'BeneID' column of test_beneficiary.

In [23]:
# Rename the 'county' column to 'country' in the test_beneficiary dataset
test_beneficiary = test_beneficiary.rename(columns={'County': 'Country'})

# Verify the change
print(test_beneficiary.columns)

Index(['BeneID', 'DOB', 'DOD', 'Gender', 'Race', 'RenalDiseaseIndicator',
       'State', 'Country', 'NoOfMonths_PartACov', 'NoOfMonths_PartBCov',
       'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
       'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
       'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
       'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
       'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
       'ChronicCond_stroke', 'IPAnnualReimbursementAmt',
       'IPAnnualDeductibleAmt', 'OPAnnualReimbursementAmt',
       'OPAnnualDeductibleAmt'],
      dtype='object')

In [24]:
# List of columns that need to be converted
chronic_conditions = [
    'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
    'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
    'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
    'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
    'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
    'ChronicCond_stroke'
]

# Convert 2 to 0 and leave 1 as 1 for the specified columns
test_beneficiary[chronic_conditions] = test_beneficiary[chronic_conditions].replace({2: 0})

# Verify the changes
display(test_beneficiary[chronic_conditions].head())

,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke
0,1,0,1,0,0,1,1,1,0,1,1
1,1,1,0,0,0,0,1,0,1,1,0
2,0,1,0,1,1,0,1,1,1,0,0
3,0,1,1,0,0,1,1,0,0,1,1
4,0,1,1,0,1,1,0,1,0,0,0

In [25]:
# If you have the same column in the test_beneficiary dataset, apply the same transformation
test_beneficiary['RenalDiseaseIndicator'] = test_beneficiary['RenalDiseaseIndicator'].replace({0: 'N'})

# Verify the changes
print(test_beneficiary['RenalDiseaseIndicator'].value_counts())

RenalDiseaseIndicator
N    53408
Y    10560
Name: count, dtype: int64

In [26]:
# Replace 1 with 'M' and 2 with 'F' in the gender column for train_beneficiary
# If you have the same column in the test_beneficiary dataset, apply the same transformation
test_beneficiary['Gender'] = test_beneficiary['Gender'].replace({1: 'M', 2: 'F'})

#Verify the changes
print(test_beneficiary['Gender'].value_counts())

Gender
F    36721
M    27247
Name: count, dtype: int64

In [27]:
display(test_beneficiary)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,Country,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,Alive,M,1,N,39,230,12,12,...,1,1,1,0,1,1,36000,3204,60,70
1,BENE11007,1940-09-01,2009-12-01 00:00:00,M,2,N,45,610,12,12,...,0,1,0,1,1,0,0,0,1490,160
2,BENE11010,1936-07-01,Alive,F,1,N,41,30,12,12,...,0,1,1,1,0,0,0,0,1170,660
3,BENE11011,1914-03-01,Alive,F,2,N,1,360,12,12,...,1,1,0,0,1,1,5000,1068,250,320
4,BENE11014,1938-04-01,Alive,F,1,Y,45,780,12,12,...,1,0,1,0,0,0,21260,2136,120,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63963,BENE159187,1959-07-01,Alive,M,1,N,27,140,12,12,...,1,1,1,0,0,0,0,0,2650,450
63964,BENE159193,1936-12-01,Alive,F,1,N,36,170,12,12,...,0,0,0,0,0,0,0,0,110,50
63965,BENE159194,1939-07-01,Alive,M,1,N,39,140,12,12,...,0,0,0,0,0,0,0,0,430,460
63966,BENE159196,1916-06-01,Alive,F,1,N,6,150,12,12,...,1,1,1,0,0,0,2000,1068,3240,1390
63967,BENE159197,1930-01-01,Alive,M,1,N,16,560,12,12,...,0,0,1,0,0,0,0,0,2650,10

#Data cleaning process for Inpatient data

In [28]:
display(train_inpatient)

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,...,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,NaN,2009-08-31,...,NaN,NaN,NaN,NaN,7092.0,NaN,NaN,NaN,NaN,NaN
2,BENE11001,CLM68358,2009-09-17,2009-09-20,PRV56046,5000,PHY372395,NaN,PHY324689,2009-09-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BENE11011,CLM38412,2009-02-14,2009-02-22,PRV52405,5000,PHY369659,PHY392961,PHY349768,2009-02-14,...,25062,40390,4019,NaN,331.0,NaN,NaN,NaN,NaN,NaN
4,BENE11014,CLM63689,2009-08-13,2009-08-30,PRV56614,10000,PHY379376,PHY398258,NaN,2009-08-13,...,5119,29620,20300,NaN,3893.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40469,BENE159167,CLM69886,2009-09-28,2009-10-02,PRV53671,7000,PHY345332,PHY319565,NaN,2009-09-28,...,79092,70704,2869,4148,9904.0,NaN,NaN,NaN,NaN,NaN
40470,BENE159175,CLM74504,2009-11-03,2009-11-06,PRV54981,4000,PHY342806,PHY365497,NaN,2009-11-03,...,49122,4254,5990,NaN,8605.0,NaN,NaN,NaN,NaN,NaN
40471,BENE159177,CLM76485,2009-11-18,2009-11-22,PRV56588,3000,PHY423220,PHY332752,NaN,2009-11-18,...,71534,71590,V4502,NaN,9390.0,NaN,NaN,NaN,NaN,NaN
40472,BENE159177,CLM79949,2009-12-17,2009-12-18,PRV56575,5000,PHY353156,NaN,NaN,2009-12-17,...,4263,414,41400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40473,BENE159188,CLM69948,2009-09-28,2009-10-06,PRV54765,15000,PHY431177,PHY352941,NaN,2009-09-28,...,4019,2800,27801,NaN,1733.0,NaN,NaN,NaN,NaN,NaN

In [29]:
train_inpatient.shape

(40474, 30)

In [30]:
display(train_outpatient)

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,ClmDiagnosisCode_1,...,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DeductibleAmtPaid,ClmAdmitDiagnosisCode
0,BENE11002,CLM624349,2009-10-11,2009-10-11,PRV56011,30,PHY326117,NaN,NaN,78943,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,56409
1,BENE11003,CLM189947,2009-02-12,2009-02-12,PRV57610,80,PHY362868,NaN,NaN,6115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,79380
2,BENE11003,CLM438021,2009-06-27,2009-06-27,PRV57595,10,PHY328821,NaN,NaN,2723,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
3,BENE11004,CLM121801,2009-01-06,2009-01-06,PRV56011,40,PHY334319,NaN,NaN,71988,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
4,BENE11004,CLM150998,2009-01-22,2009-01-22,PRV56011,200,PHY403831,NaN,NaN,82382,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,71947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517732,BENE159198,CLM510792,2009-08-06,2009-08-06,PRV53699,800,PHY364188,PHY364188,PHY385752,2163,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
517733,BENE159198,CLM551294,2009-08-29,2009-08-29,PRV53702,400,PHY423019,PHY332284,NaN,7041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
517734,BENE159198,CLM596444,2009-09-24,2009-09-24,PRV53676,60,PHY361063,NaN,NaN,V570,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
517735,BENE159198,CLM636992,2009-10-18,2009-10-18,PRV53689,70,PHY403198,NaN,PHY419379,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
517736,BENE159198,CLM686139,2009-11-17,2009-11-18,PRV53689,80,PHY419379,NaN,PHY419379,78900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN

In [31]:
train_outpatient.shape

(517737, 27)

In [32]:
# Check for missing values
missing_values = train_inpatient.isnull().sum()
print(missing_values)

BeneID                        0
ClaimID                       0
ClaimStartDt                  0
ClaimEndDt                    0
Provider                      0
InscClaimAmtReimbursed        0
AttendingPhysician          112
OperatingPhysician        16644
OtherPhysician            35784
AdmissionDt                   0
ClmAdmitDiagnosisCode         0
DeductibleAmtPaid           899
DischargeDt                   0
DiagnosisGroupCode            0
ClmDiagnosisCode_1            0
ClmDiagnosisCode_2          226
ClmDiagnosisCode_3          676
ClmDiagnosisCode_4         1534
ClmDiagnosisCode_5         2894
ClmDiagnosisCode_6         4838
ClmDiagnosisCode_7         7258
ClmDiagnosisCode_8         9942
ClmDiagnosisCode_9        13497
ClmDiagnosisCode_10       36547
ClmProcedureCode_1        17326
ClmProcedureCode_2        35020
ClmProcedureCode_3        39509
ClmProcedureCode_4        40358
ClmProcedureCode_5        40465
ClmProcedureCode_6        40474
dtype: int64

In [33]:
# Fill missing values with 'N' for all columns except DeductibleAmtPaid
columns_to_fill = [col for col in train_inpatient.columns if col != 'DeductibleAmtPaid']
train_inpatient[columns_to_fill] = train_inpatient[columns_to_fill].fillna('N')

# Verify that there are no more missing values
missing_values_after = train_inpatient.isnull().sum()
print(missing_values_after)

BeneID                      0
ClaimID                     0
ClaimStartDt                0
ClaimEndDt                  0
Provider                    0
InscClaimAmtReimbursed      0
AttendingPhysician          0
OperatingPhysician          0
OtherPhysician              0
AdmissionDt                 0
ClmAdmitDiagnosisCode       0
DeductibleAmtPaid         899
DischargeDt                 0
DiagnosisGroupCode          0
ClmDiagnosisCode_1          0
ClmDiagnosisCode_2          0
ClmDiagnosisCode_3          0
ClmDiagnosisCode_4          0
ClmDiagnosisCode_5          0
ClmDiagnosisCode_6          0
ClmDiagnosisCode_7          0
ClmDiagnosisCode_8          0
ClmDiagnosisCode_9          0
ClmDiagnosisCode_10         0
ClmProcedureCode_1          0
ClmProcedureCode_2          0
ClmProcedureCode_3          0
ClmProcedureCode_4          0
ClmProcedureCode_5          0
ClmProcedureCode_6          0
dtype: int64

In [34]:
# Replace missing values in DeductibleAmtPaid with "0"
train_inpatient['DeductibleAmtPaid'] = train_inpatient['DeductibleAmtPaid'].fillna('0.0')

# Verify that there are no more missing values in the DeductibleAmtPaid column
missing_values_after = train_inpatient['DeductibleAmtPaid'].isnull().sum()
print(f"Missing values in DeductibleAmtPaid after filling: {missing_values_after}")

Missing values in DeductibleAmtPaid after filling: 0

In [35]:
# Check for missing values
missing_values = train_outpatient.isnull().sum()
print(missing_values)

BeneID                         0
ClaimID                        0
ClaimStartDt                   0
ClaimEndDt                     0
Provider                       0
InscClaimAmtReimbursed         0
AttendingPhysician          1396
OperatingPhysician        427120
OtherPhysician            322691
ClmDiagnosisCode_1         10453
ClmDiagnosisCode_2        195380
ClmDiagnosisCode_3        314480
ClmDiagnosisCode_4        392141
ClmDiagnosisCode_5        443393
ClmDiagnosisCode_6        468981
ClmDiagnosisCode_7        484776
ClmDiagnosisCode_8        494825
ClmDiagnosisCode_9        502899
ClmDiagnosisCode_10       516654
ClmProcedureCode_1        517575
ClmProcedureCode_2        517701
ClmProcedureCode_3        517733
ClmProcedureCode_4        517735
ClmProcedureCode_5        517737
ClmProcedureCode_6        517737
DeductibleAmtPaid              0
ClmAdmitDiagnosisCode     412312
dtype: int64

In [36]:
# Replace all missing values in train_outpatient with "N"
train_outpatient = train_outpatient.fillna('N')

# Verify that there are no more missing values
missing_values_after = train_outpatient.isnull().sum()
print(missing_values_after)

BeneID                    0
ClaimID                   0
ClaimStartDt              0
ClaimEndDt                0
Provider                  0
InscClaimAmtReimbursed    0
AttendingPhysician        0
OperatingPhysician        0
OtherPhysician            0
ClmDiagnosisCode_1        0
ClmDiagnosisCode_2        0
ClmDiagnosisCode_3        0
ClmDiagnosisCode_4        0
ClmDiagnosisCode_5        0
ClmDiagnosisCode_6        0
ClmDiagnosisCode_7        0
ClmDiagnosisCode_8        0
ClmDiagnosisCode_9        0
ClmDiagnosisCode_10       0
ClmProcedureCode_1        0
ClmProcedureCode_2        0
ClmProcedureCode_3        0
ClmProcedureCode_4        0
ClmProcedureCode_5        0
ClmProcedureCode_6        0
DeductibleAmtPaid         0
ClmAdmitDiagnosisCode     0
dtype: int64